version: "3.5"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: '/home/pauberna/data/Wordpress'
      o: 'bind'
      type: 'none'
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: '/home/pauberna/data/DB'
      o: 'bind'
      type: 'none'

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
    expose:
      - "9000"
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
    expose:
      - "3306"